obstacle_range: 4.0
raytrace_range: 3.0
#robot_radius: 0.3

footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
footprint_inflation: 0.8

inflation_radius: 0.9
cost_scaling_factor: 100
max_obstacle_height: 2.0 
min_obstacle_height: 0.0 
observation_sources: scan
scan: {data_type: LaserScan, topic: /front/scan, marking: true, clearing: true, expected_update_rate: 0}
