obstacle_range: 5.0
raytrace_range: 3.0
#robot_radius: 0.3

footprint: [[1, 1], [1, -1], [-1, -1], [-1, 1]]
footprint_inflation: 1

inflation_radius: 5
cost_scaling_factor: 200
max_obstacle_height: 2.0 
min_obstacle_height: -1.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /front/scan, marking: true, clearing: true, expected_update_rate: 0}
