obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.4

footprint: [[0.3, 0.3], [0.3, -0.3], [-0.3, -0.3], [-0.3, 0.3]]
footprint_inflation: 0.1

inflation_radius: 0.2
max_obstacle_height: 1.0 
min_obstacle_height: 0.0 
observation_sources: scan
scan: {data_type: LaserScan, topic: /front/scan, marking: true, clearing: true, expected_update_rate: 0}
